/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boot.app;

import test.lib.Library2;

public class Library {
    public boolean someLibraryMethod() {
    	new Library2();
        return true;
    }
}
